spring.application.name=ss12_01


#Phần 1 - Phân tích
#1. Vì sao spring-boot-starter-web được gọi là “Starter”?
#
#spring-boot-starter-web được gọi là Starter vì nó là một “gói khởi động” đã được Spring Boot đóng gói sẵn để phát triển ứng dụng Web.
#
#Thay vì phải tự tìm và khai báo từng thư viện riêng lẻ, chỉ cần thêm một dependency duy nhất là:
#
#implementation 'org.springframework.boot:spring-boot-starter-web'
#
#Spring Boot sẽ tự động kéo theo các thư viện cần thiết cho ứng dụng Web.
#
#2. Nó giúp chúng ta không phải khai báo các thư viện nhỏ lẻ nào?
#
#Khi dùng spring-boot-starter-web, chúng ta không cần tự thêm riêng từng thư viện như:
#
#Web MVC
#Spring MVC
#Spring Web
#JSON
#Jackson Databind
#Jackson Core
#Validation
#Jakarta Validation API
#Logging
#SLF4J
#Logback
#Embedded Server
#Embedded Tomcat
#Các thư viện hỗ trợ khác
#Spring Context
#Spring Beans
#Spring Core
#3. Lợi ích của Starter
#Giảm cấu hình phức tạp
#
#Không cần tự quản lý hàng chục dependency.
#
#Tự động tương thích phiên bản
#
#Spring Boot tự chọn các version phù hợp với nhau.
#
#Khởi tạo nhanh
#
#Tạo project Web chạy được ngay chỉ sau vài phút.
#
#Tích hợp Embedded Server
#
#Không cần cài Tomcat rời vì Tomcat đã được nhúng sẵn trong ứng dụng.